"""First

Revision ID: 1813197beeb5
Revises: 9bc077b3df48
Create Date: 2021-11-18 15:24:12.126230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1813197beeb5'
down_revision = '9bc077b3df48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
