"""First

Revision ID: 2c721a9f0326
Revises: 309b9f506c0a
Create Date: 2021-11-18 15:42:27.990623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c721a9f0326'
down_revision = '309b9f506c0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
