"""First

Revision ID: 309b9f506c0a
Revises: 1813197beeb5
Create Date: 2021-11-18 15:37:37.453752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '309b9f506c0a'
down_revision = '1813197beeb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
