"""First

Revision ID: 9bc077b3df48
Revises: 3dd84f5bd046
Create Date: 2021-11-18 15:09:38.054918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bc077b3df48'
down_revision = '3dd84f5bd046'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
