"""First

Revision ID: e103f87999de
Revises: cdc9d6affa3a
Create Date: 2021-11-18 16:50:48.341797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e103f87999de'
down_revision = 'cdc9d6affa3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
