"""First

Revision ID: e56d5c2e3896
Revises: c84ce608ce3d
Create Date: 2021-11-18 16:32:13.459311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e56d5c2e3896'
down_revision = 'c84ce608ce3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
